apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: rook-ceph
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/mnt/test"
      name: test-storage
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: test-pvc
