# master2-rook-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rook-ceph
  name: master2-rook-role
rules:
- apiGroups: [""]          # core API grup
  resources: ["pods", "services", "configmaps"]  # erişmesini istediğin kaynaklar
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
